### ISSUE TITLE
Licensing of the documentation

### ISSUE THREAD

**Issue by seabass-labrax** [windmill-labs/windmilldocs#137]
I'd like to contribute to this documentation, but I noted that there doesn't appear to be a stated licence for the content anywhere in the repository. Please consider releasing the documentation under free culture terms, using for instance the [Creative Commons Attribution Share Alike 4.0 International](https://spdx.org/licenses/CC-BY-SA-4.0.html) licence. The Git log would suggest that you've accepted external contributions in the past, so you may be unable to unilaterally license this repository; in that case, you would have to obtain permission from their authors or revert the commits.

**Comment by rubenfiszel** [comment]
@seabass-labrax you're right and that's now fixed, we are cc-by-sa 4.0 now :)

Thank you for the suggestion!
