### ISSUE TITLE
Triggering Flows : Link to webhooks not working

### ISSUE THREAD

**Issue by Haibread** [windmill-labs/windmilldocs#301]
Hello,

On the Triggering Flows page, the link to "Trigger Flows from Webhooks" does not redirect anywhere.

Link to the page : https://www.windmill.dev/docs/getting_started/trigger_flows

The link that is not working : https://www.windmill.dev/docs/getting_started/trigger_flows#trigger-flows-from-webhooks

Might probably be : https://www.windmill.dev/docs/getting_started/trigger_flows#webhooks

Thanks

**Comment by hcourdent** [comment]
Hi @Haibread ! Thanks for reporting :)

This will be fixed when https://github.com/windmill-labs/windmilldocs/pull/302 is merged

Best,
