### ISSUE TITLE
Revamp landing page

### ISSUE THREAD

**Issue by malomarrec** [windmill-labs/windmilldocs#34]
## Problem

The top of the landing page is too crowded and overwhelming. We don't have metrics setup for CTAs and bounce rate to my knowledge (WIP), but I think this is hurting the page performance.

<img width="1713" alt="Screenshot 2022-10-08 at 16 58 58" src="https://user-images.githubusercontent.com/25070988/194714606-5c629e89-7c09-4ef3-88e3-016c4bb18290.png">

### First screen/section

**There are 3 CTAs. That's at least one too many.** 

- [ ] keep only Try Cloud App (main) and schedule a demo (secondary)
- [ ] move get started to menu bar (for users that want to read the docs first)
- [ ] add get started later in the flow if needed (post signup)

**There's two text blocks that are overwhelming and distracting (green)**

Keep one of them only. Input needed @rubenfiszel : what's the most asked question? "what is it that you do?" or "how different are you from list"
- [ ] remove the least important one (and potentially move it to another view when you scroll down)

** Distracting subtext(purple)**

This subtext is too much, and is adding to the feeling of crowdedness. Either remove all the green text, and keep this without the parenthesis. Or remove it.
- [ ] TBD

### What can you build with Windmill?

- [ ] TBD, I'll propose some tweaks to make it more concise / striking

### Whom is it for section

"write like you speak", suggest we keep it conversational
- [ ] whom -> who 
- [ ] rewrite copy to make it more concise (max 3 sentences per target group)

### Feature list section

"ALL-IN-ONE PLATFORM TO POWER YOUR ENTIRE BACKOFFICE"

- Everything should fit in one screen
- [ ] remove extraneous blocks
- [ ] remove extraneous enumeration of features "serverless runtime + autogenerated UI to share your app + flow builder + schedules + secrets + groups + permissions + OAuth integrations + ..."

![image](https://user-images.githubusercontent.com/25070988/194715065-3a1cf106-d65e-44c8-b79e-18d297338f95.png)

### How it works

"Turn scripts into shareable internal apps or complex workflows triggered by webhooks, a schedule, or watching for new events."

- [ ] add title to section
- [ ] make text more concise
- [ ] consider replacing confusing images with a small GIF
- [ ] needs to fit on a single screen

### Replace all your sparely used niche tools: We cover every use-case and to any API

This section is not very useful. When users have scrolled here, if they didn't get the value prop, it's already game over.
- [ ] remove section

### Architecture section

- [ ] remove section, move to docs (any strong feelings @rubenfiszel ?)

### Audit logs

This feels superfluous, and is inconsistent with the rest of the page

- [ ] remove, and add to the feature list section (link to docs for details)

**Comment by rubenfiszel** [comment]
All the points are good and will be applied at next cycle of landing page rework.

What do we do can be moved in a below section
Architecture moved to docs make sense to me

The too many CTAs seem a bit odd to me, it seems there is a clear one being highlighted "try the app" and the other ones are in decreasing order of priority. The docs if you don't wanna bother signing up to the app and a way to schedule a call without too much hassle. How would you suggest reworking that ?
